language: python
python:
- '3.9'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: fa6ka2WJXR5+Lbfb5xkfnccDU/zY0h7lJbc+jUkagE2MTIuVxzG3nlfb4aiSaP9jDK7byBGOKyXFTQgQ+sZVa+OUHv+p8t6ItfJCGL+f15PVA5IO2NETnsgnDSieA6rQ7fhPM2+SZXgz6mjRz791g9B6yiPjJF9F8gmuKIX61RS5Fhl4c4Mzhf9332AgfPKimXtSbRcw4es7XHGOS7F4m+b7/isIc9filbdYz/eC5CYHmJ/SQKs30DRLVnA632Iz4f1PJYttYe2jar3vlui386gKdUnhFWL6lLmjdRqG0WAcdv1S/TD/SA6djt+2+FrPVmd33TeQBfA1j0G6hczafM658qnoJZkomiGLxTqAIUglIwo/SZxa+2W3N5pNVJaNHx5FgAC23zkx2g0AQIbNQsUZw/SCgotiWGASh5i8fjPZn/p2doVirSxmy3dJ7yiOhq7ULKC9Ma0izuhnnrQ4KQ+gmdVPyqXIGd1oZ12IAIONUPCLb4TV2NgVdze9UMh93Dshl8ElG7n1UIZp1xf+/StQxL1fw/tshCm179LNwWdS95r7095APX2dTt6ZZ9f4qoVY8JwEYXVp36nK/SOix4JFThtSlQkr3UpAK8N0a16x66tHi0cUKEyChM1LawrZwCRda6aeNKBP2ij6h2j+Q+4Gqi9FmvHQ9noK1EJj97g=
  app: roommate-finder-a-22
  on:
    repo: uva-cs3240-s21/project-a-22
