# Generated by Django 3.1.6 on 2021-04-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
