# Generated by Django 3.1.6 on 2021-04-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
