# Generated by Django 3.1.6 on 2021-04-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_auto_20210419_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.DateField(default='2021-04-19', help_text='YYYY-MM-DD'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(help_text='HH:MM'),
        ),
        migrations.AlterField(
            model_name='event',
            name='zoom_link',
            field=models.URLField(blank=True),
        ),
    ]
