# Generated by Django 3.1.7 on 2021-03-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_auto_20210323_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='go_to_bed',
            field=models.CharField(choices=[('1', 'Before 9pm'), ('2', '9pm-10:30pm'), ('3', '10:30pm-12:00am'), ('4', '12:00am-1:30am'), ('5', 'After 1:30am')], default='Before 9pm', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='guests',
            field=models.CharField(choices=[('1', 'Always love to have guests over'), ('2', 'Usually love to have guests over'), ('3', 'Sometimes love to have guests over'), ('4', 'Never love to have guests over')], default='Always love to have guests over', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='how_clean',
            field=models.CharField(choices=[('1', 'Very Clean'), ('2', 'Kinda Clean'), ('3', 'Kinda Messy'), ('4', 'Very Messy')], default='Very Clean', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='ideal_rent',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='more_introverted_or_extroverted',
            field=models.CharField(choices=[('1', 'Introverted'), ('2', 'Extroverted'), ('3', 'In the middle')], default='Introverted', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='wake_up',
            field=models.CharField(choices=[('1', 'Before 7am'), ('2', '7am-8:30am'), ('3', '8:30am-10am'), ('4', '10am-11:30am'), ('5', 'After 11:30am')], default='Before 7am', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='year',
            field=models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th')], max_length=50),
        ),
    ]
