# Generated by Django 3.1.6 on 2021-05-06 04:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_auto_20210506_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.FloatField(choices=[('1', '0.25'), ('2', '0.5'), ('3', '0.75'), ('4', '1.0')], default=1.0),
        ),
        migrations.AlterField(
            model_name='question',
            name='ideal_rent',
            field=models.PositiveBigIntegerField(help_text='Do not use "$" or "," in your answer', validators=[django.core.validators.MinValueValidator(200, message='Please enter a number above 200'), django.core.validators.MaxValueValidator(1500, message='Please enter a number below 1500')]),
        ),
    ]
