# Generated by Django 3.1.5 on 2021-05-06 13:53

from django.db import migrations, models
import questionnaire.models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_auto_20210506_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.DateField(help_text='MM/DD/YYYY', validators=[questionnaire.models.day_validator]),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(help_text='HH:MM AM/PM', validators=[questionnaire.models.time_validator]),
        ),
    ]
